### PR TITLE
Fix hash for mavericks binary

### PR DESCRIPTION
**Pull request by ratkins**

### CODE REVIEW

**Comment by jeantil** [comment]
Hi @ratkins 

sorry I didn't address this earlier, I somehow missed it. Do you think it still makes sense ?

thanks

**Comment by ratkins** [comment]
Honestly I can't remember 😑. I guess so, unless you've actually updated the bottle including the binary in the meantime?

**Comment by jeantil** [comment]
wel, I don't remember either but 
`curl -s -L https://github.com/jeantil/autokbisw/archive/1.2.0.tar.gz | sha256sum`
yelds 
`1c3bfad19b9025ad15f01ea0554351f47225807efd85cb4b4f0b6e1785af3f3e  - `
so i guess the current value is ok

**Comment by ratkins** [comment]
Yeah, I guess brew would be complaining if the sha didn't match anyway. Closing.

**Pull request closed without merging**
